version: "3.8"
services:
  elasticsearch:
    image: "elasticsearch:7.17.0"
    environment:
      discovery.type: "single-node"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - "elasticsearch-data:/usr/share/elasticsearch/data"
  kibana:
    image: "kibana:7.17.0"
    ports:
      - "5601:5601"

volumes:
  elasticsearch-data: